### ISSUE TITLE
Custom entities

### ISSUE THREAD

**Issue by dadodasyra** [HisteriaMC/HisteriaPack#90]
Il faut implémenter les custom entities coté "code" du pack avec la bonne texture pour :
- histeria:grapling_hook
- histeria:shuriken
- histeria:dynamite

Exemple, dans /entity/
```yaml
{
  "format_version": "1.10.0",
  "minecraft:client_entity": {
    "description": {
      "identifier": "histeria:dynamite",
      "materials": {
        "default": "egg"
      },
      "textures": {
        "default": "textures/chemin/dynamite"
      },
      "geometry": {
        "default": "geometry.item_sprite"
      },
      "render_controllers": [ "controller.render.item_sprite" ],
      "animations": {
        "flying": "animation.actor.billboard"
      },
      "scripts": {
        "animate": [
          "flying"
        ]
      }
    }
  }
} 
```
